version:
  name: velociraptor
  version: 0.7.1-1
  commit: 2d7d6cf
  build_time: "2023-12-27T09:45:45Z"
  install_time: 1712583397
  ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/7337099704
  compiler: go1.21.5
Client:
  server_urls:
  - https://velociraptor-api.apps.shelter-fr-dev.camptocamp.com/
  ca_certificate: |
    -----BEGIN CERTIFICATE-----
    MIIDSzCCAjOgAwIBAgIQLXEJHKGNwUB7pc2HrGs6XDANBgkqhkiG9w0BAQsFADAa
    MRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwHhcNMjQwNDA4MTMzNzExWhcNMzQw
    NDA2MTMzNzExWjAaMRgwFgYDVQQKEw9WZWxvY2lyYXB0b3IgQ0EwggEiMA0GCSqG
    SIb3DQEBAQUAA4IBDwAwggEKAoIBAQDex9eOvOtzqoosYdTzXL8f8P88CH9au1vA
    VHJHMQAIHlQIHGKSMQW+uT5NMidV447K1xxLfuOTf4+n1iqaG4ipwfGzQNe/UpnV
    vty9PK1x3NVF6Mw7OVjvQFGFi6vdl8jNbF3MQ5vY+4pcvSUESIKa4RdYq6sRu6GR
    50q8uRliv2KRyiIKqE0Yk8EI8AKtVwY3u+Fkuwt1Ophhf2JiRk4bQn3rGQKXwIxQ
    FJW92kk8W9Idm6SjWr69aTI4mLNUo6nqzv9GWaeTa+NEX23JIwksl+BoD+CUyOrd
    MCAlFb8IAT9yLKcsvinPmRwsb1zmWfAl2Y/sySOQ3XcRrjtdJ8AZAgMBAAGjgYww
    gYkwDgYDVR0PAQH/BAQDAgKkMB0GA1UdJQQWMBQGCCsGAQUFBwMBBggrBgEFBQcD
    AjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ987vyzWp0S/iZQpA8I+xlKgwb
    iTAoBgNVHREEITAfgh1WZWxvY2lyYXB0b3JfY2EudmVsb2NpZGV4LmNvbTANBgkq
    hkiG9w0BAQsFAAOCAQEAULtabdmf46kZpaEifMnqpSwbPtRqnsQ8/QabKNfpG7AL
    NIT9kYpxHQtgnpO35gSvBrphl05VMPM79zozzU49JgngrgObZsSCnVNPBBp4dVDy
    xi0CpHk/eLv/l6dkB6JMSMHz5eSL313keVakcsjLtlsR/DP4+yqF7OH6dLs+orTX
    N+GZC/wJvdaCk+KJiU/FrPf6yXnnXW6BTI0DqOphF5wnVwQb5ckeDR/Imxtn1cXv
    BUHcur/P97pfYGwcRMtnVToVJdVQnRSmBsSI/1evIh2cc2jdetMzz6XNEwtyUYn/
    f5DYFaLz8XvfYUZk9vpXxbxhotMyrVVlR/3uZZe+pg==
    -----END CERTIFICATE-----
  nonce: nIPsfnr25L0=
  writeback_darwin: /etc/velociraptor.writeback.yaml
  writeback_linux: /etc/velociraptor.writeback.yaml
  writeback_windows: $ProgramFiles\Velociraptor\velociraptor.writeback.yaml
  level2_writeback_suffix: .bak
  tempdir_windows: $ProgramFiles\Velociraptor\Tools
  max_poll: 60
  nanny_max_connection_delay: 600
  windows_installer:
    service_name: Velociraptor
    install_path: $ProgramFiles\Velociraptor\Velociraptor.exe
    service_description: Velociraptor service
  darwin_installer:
    service_name: com.velocidex.velociraptor
    install_path: /usr/local/sbin/velociraptor
  version:
    name: velociraptor
    version: 0.7.1-1
    commit: 2d7d6cf
    build_time: "2023-12-27T09:45:45Z"
    install_time: 1712583397
    ci_build_url: https://github.com/Velocidex/velociraptor/actions/runs/7337099704
    compiler: go1.21.5
  use_self_signed_ssl: false
  pinned_server_name: VelociraptorServer
  max_upload_size: 5242880
  local_buffer:
    memory_size: 52428800
    disk_size: 1073741824
    filename_linux: /var/tmp/Velociraptor_Buffer.bin
    filename_windows: $TEMP/Velociraptor_Buffer.bin
    filename_darwin: /var/tmp/Velociraptor_Buffer.bin